### ISSUE TITLE
Fix collapsible

### ISSUE THREAD

**Issue by marina-chibizova** [1712n/dn-institute#266]
JS collapsible doesn't work on some devices, let's switch to the basic functionality of hugo-native collapsible and see when it's not enough and we need something else

**Comment by danisztls** [comment]
@marina-chibizova

The menu code in use has a structure that isn't suitable for using the collapsible method that the theme uses so this change wouldn't be so trivial to implement. The `<input>+<label>`  method is a hack, it isn't semantic and will pose an accessibility issue for persons using screen readers & crawlers and may not work properly on some devices.

The collapsible items were working before for you, right? I suggest that instead I backtrack on the recent changes until it works for you as this will be easier to do and will allow me to find & fix the root cause. Do you know whether the PR #255 or #256 is to blame?

I've retested the site in all major browsers and operating systems. Unfortunately, I was unable to replicate the issue on my end. :/

**Comment by evgenydmitriev** [comment]
> The menu code in use has a structure that isn't suitable for using the collapsible method that the theme uses so this change wouldn't be so trivial to implement. The <input>+<label> method is a hack, it isn't semantic and will pose an accessibility issue for persons using screen readers & crawlers and may not work properly on some devices.

For now, the menu doesn't work in any browsers on my desktop (Fedora + Chrome, Fedora + Firefox).

![image](https://github.com/1712n/dn-institute/assets/56804873/e7a56265-80ca-4a1e-8b8f-ffb7e2542e25)

Works on Android + Chrome though.

Let's switch back whatever is implemented in the theme and commit improvements to their repo if you think you can make it better.

**Comment by marina-chibizova** [comment]
> The collapsible items were working before for you, right?

They were actually never working for me. I only remember It working initially when we were setting up the site. I am not sure which PR caused a problem, I saw all the subsections of Infrastructure resilience as an always opened menu, and now it's just hidden and impossible to open at all, there was never a stage for me when collapsible worked

**Comment by danisztls** [comment]
> Let's switch back whatever is implemented in the theme and commit improvements to their repo if you think you can make it better.

I can submit PRs to the theme. So, ideally, we have only configuration downstream.
